#theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes@4.19.1"
title: Makita Lab - Robotic Manipulation and Hand Mechanics Research

lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
